<?php

return [
    [
        'id'=>1,
        'client_id'=>1000,
        'created_at' => '1391885313',
        'updated_at' => '1391885313',
        'name' => 'Rent4b',
        'status' => \rent\entities\Client\Site::STATUS_ACTIVE,
        'domain' => 'rent4b',
        'mainPage_json' => '{}',
        'footer_json' => '{}',
        'counter_json' => '{}',
        'reCaptcha_json' => '{}',
        'meta_json' => '{}',
        'timezone' => 'Europe/Moscow',
    ],
    [
        'id'=>1000,
        'client_id'=>1000,
        'created_at' => '1391885313',
        'updated_at' => '1391885313',
        'name' => 'Сайт Газпрома',
        'status' => \rent\entities\Client\Site::STATUS_ACTIVE,
        'domain' => 'gazprom.ru',
        'mainPage_json' => '{}',
        'footer_json' => '{}',
        'counter_json' => '{}',
        'reCaptcha_json' => '{}',
        'meta_json' => '{}',
        'timezone' => 'Europe/Moscow',
    ],
    [
        'id'=>2000,
        'client_id'=>2000,
        'created_at' => '1391885313',
        'updated_at' => '1391885313',
        'name' => 'Сайт компании Рога и копыта',
        'status' => \rent\entities\Client\Site::STATUS_ACTIVE,
        'domain' => 'roga.ru',
        'mainPage_json' => '{}',
        'footer_json' => '{}',
        'counter_json' => '{}',
        'reCaptcha_json' => '{}',
        'meta_json' => '{}',
        'timezone' => 'Europe/Moscow',
    ],
];
